---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  log_level: auto

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: ubuntu-16.04
  - name: centos-7.1
  - name: centos-7.2
  - name: debian-8.5
  - name: debian-8.1

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[droneio::default]
    attributes:
      drone:
        port: 1234
        remote:
          driver: gitlab
          config: https://example.com/fakeremoteconfig
        database:
          driver: sqlite3
          config: /var/lib/drone/kitchen.sqlite
