---
driver:
  name: vagrant
  vm_hostname: example.com
  network:
    - ["private_network", {type: "dhcp"}]

provisioner:
  name: chef_solo
  log_level: auto

verifier:
  name: inspec

platforms:
  - name: geerlingguy/ubuntu1604
# - name: ubuntu-16.04
    driver_config:
      customize:
        cpus: 2
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[boulder_server]
      - recipe[drone_app::default]
    attributes:
      boulder:
        revision: 2d33a9900cafe82993744fe73bd341fe47df2171
      letsencrypt:
        server: http://127.0.0.1:4000/directory
        contact: fake@example.com
      drone:
        version: '0.4'
        port: '1234'
        config:
          remote_driver: gitlab
          remote_config: https://example.com/fakeremoteconfig
          database_driver: sqlite3
          database_config: /var/lib/drone/kitchen.sqlite
